### ISSUE TITLE
Proposal: typeclass and newtype for working with xpaths more easily:

### ISSUE THREAD

**Issue by bbarker** [purescript-web/purescript-web-dom-xpath#3]
```purescript
class Semigroup m <= XPathLike m where
  pathAppend :: m -> m -> m
  pathAppendNSx :: m -> m -> m
  root :: m

newtype XPath = XPath String
derive instance newtypeXPath :: Newtype XPath _

instance stringXPath :: XPathLike String where
  pathAppend p1 p2 = p1 <> "/" <> p2
  pathAppendNSx p1 p2 = p1 <> "/x:" <> p2
  root = "/"

infixr 5 pathAppend as //
infixr 5 pathAppendNSx as /?
```

This would allow us to easily construct paths like:

```purescript
root /? "record" /? identifier -- == "/x:record/x:identifier"
```

I expect more operations can be added.

**Comment by bbarker** [comment]
Actually, now that I think about it, the newtype is just an extra annoyance - I should try the class on String directly.

**Comment by bbarker** [comment]
Also maybe the typeclass itself is largely unnecessary, could probably still use infix operators above imported from an XPath.Syntax module. Can't imagine doing this for anything other than String (as this isn't Haskell), and maybe a no-class implementation would be more efficient

**Comment by hdgarrood** [comment]
I think “classy” APIs are often sensible, but it’s usually simpler to build a classy API on top of one which doesn’t use classes rather than the other way around, so I think avoiding classes in the basic set of bindings is generally the better approach. See dom versus dom-classy for example.

**Comment by garyb** [comment]
I'd agree very strongly with Harry on this. The reason the APIs are pretty awful in the dom libraries I've been maintaining is they're trying to be as unopinionated as possible, other than exposing the functionality from JS. It's always possible to build enhancements on top of that, but if someone designs a clever API that you don't like for whatever reason, and doesn't provide the raw stuff too, you're out of luck.

**Comment by bbarker** [comment]
OK, that sounds good to me, I'll put it in another repo. Thanks!
