### ISSUE TITLE
Remove dependency on purescript-naturals

### ISSUE THREAD

**Issue by thomashoneyman** [purescript-web/purescript-web-dom-xpath#8]
[`naturals`](https://github.com/LiamGoodacre/purescript-naturals) is not in the core or contributors organizations, so we shouldn't use it as part of the web organization. For that reason, and others discussed in #7, we should replace `Natural` as a return value with `Int` instead, and drop the dependency.

**Comment by bbarker** [comment]
Thanks again

**Comment by colinwahl** [comment]
I can take this on
